dbt_lakehouse:
  outputs:
    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: admin
      # password: [password]  # required if method is ldap or kerberos
      database: iceberg_hive
      host: localhost
      port: 8090
      schema: nemohouse
      threads: 1
      use_ssl: false


    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: [prod_user]
      password: [prod_password]  # required if method is ldap or kerberos
      database: [database name]
      host: [hostname]
      port: [port number]
      schema: [prod_schema]
      threads: [1 or more]

  target: dev

