dbt_lakehouse_dremio:
  outputs:
    dev:
      dremio_space: DBT Semantic Layer
      dremio_space_folder: Data Analytics
      object_storage_path: warehouse
      object_storage_source: Minio S3
      password: admin123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: admin
  target: dev

